name: Docker

on:
  workflow_dispatch:
  push:
    branches: [ main ]


env:
  ALIYUN_REGISTRY: "${{ secrets.ALIYUN_REGISTRY }}"
  ALIYUN_NAME_SPACE: "${{ secrets.ALIYUN_NAME_SPACE }}"
  ALIYUN_REGISTRY_USER: "${{ secrets.ALIYUN_REGISTRY_USER }}"
  ALIYUN_REGISTRY_PASSWORD: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"

jobs:

  build:
    name: Pull
    runs-on: ubuntu-latest
    steps:
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build and push image Aliyun (multi-platform)
      run: |
        docker login -u $ALIYUN_REGISTRY_USER -p $ALIYUN_REGISTRY_PASSWORD $ALIYUN_REGISTRY
        docker buildx version
        docker pull tonistiigi/binfmt
        docker run --privileged --rm tonistiigi/binfmt --install all
        for line in $(cat images.txt); do
          echo "Pulling $line..."
          docker pull $line
          image_name_tag=$(echo $line | awk -F'/' '{print $NF}')
          new_image="$ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/$image_name_tag"

          # 检查镜像是否已存在于阿里云注册表
          if docker manifest inspect $new_image > /dev/null 2>&1; then
            echo "镜像 $new_image 已存在，跳过..."
          else
            echo "如果Dockerfile不在根目录,请指定路径"
            docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t $new_image  --push .
          fi
        done
